name = "Vinox"
author = "vixeliz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "274984aff1fafdf29292689ea5736d411acb709059c43aaef1a0cb22f480b90d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"
